### ISSUE TITLE
Access-Control-Allow-Origin Problem, when using the logger

### ISSUE THREAD

**Issue by gerwald** [EEXCESS/visualization-widgets#10]
I have an issue regarding the logging.
When I am using the logger, I get the following error in my browser:
XMLHttpRequest cannot load https://eexcess-dev.joanneum.at/eexcess-privacy-proxy-issuer-1.0-SNAPSHOT/issuer/log/moduleOpened. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

As far as I know, it is possible to solve this issue, when adding the following Response header:
Access-Control-Allow-Origin: *

Interesting fact: it seems that google chrome is doing a OPTIONS-regest (instead or before the initiated POST reqeust). 
See screenshots attahed

<img width="1264" alt="error-1" src="https://cloud.githubusercontent.com/assets/183683/10633794/7ed48058-77ed-11e5-8849-c7acaf2f859b.PNG">

<img width="1046" alt="options-call" src="https://cloud.githubusercontent.com/assets/183683/10633781/6cf02982-77ed-11e5-89e3-7c7507645dd6.PNG">

**Comment by ThomasCerq** [comment]
Johannes found the problem and I applied the fix. It works now.

**Comment by gerwald** [comment]
Thanks. it now looks a little bit better :) but it still gives me an error:

XMLHttpRequest cannot load https://eexcess-dev.joanneum.at/eexcess-privacy-proxy-issuer-1.0-SNAPSHOT/issuer/log/moduleStatisticsCollected. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 500.

The OPTIONS reguest now works. but the POST request returns in an HTTP status code 500 (see screenshots below)

<img width="1187" alt="cors 1" src="https://cloud.githubusercontent.com/assets/183683/10638058/4f4d87be-7809-11e5-8304-fbc63b106fd3.PNG">
<img width="1217" alt="cors 2" src="https://cloud.githubusercontent.com/assets/183683/10638062/513d6dc8-7809-11e5-874b-75a655cb04c8.PNG">

**Comment by ThomasCerq** [comment]
What is the input?

**Comment by gerwald** [comment]
{"origin":{"clientType":"","clientVersion":"","module":"RecDashboard","userID":""},"content":[{"seq":1,"timestamp":1445434266846,"uiState":{"size":"1669/500","actFltrs":[],"browser":{"name":"Chrome","vers":46}},"action":"Dashboard opened"},{"seq":2,"timestamp":1445434271232,"uiState":{"size":"1669/500","actVis":"geochart","actFltrs":["geo"],"browser":{"name":"Chrome","vers":46}},"action":"Brush created","component":"Geochart","source":"Geochart","value":"66.79190947341796/6.6796875, 40.44694705960048/-93.8671875"},{"seq":3,"timestamp":1445434275209,"uiState":{"size":"1669/500","actVis":"geochart","actFltrs":["geo"],"browser":{"name":"Chrome","vers":46}},"action":"Brush created","component":"Geochart","source":"Geochart","value":"70.72897946208789/-72.7734375, 24.206889622398023/-126.5625"},{"seq":4,"timestamp":1445435084173,"uiState":{"size":"1669/500","actVis":"geochart","actFltrs":["geo"],"browser":{"name":"Chrome","vers":46}},"action":"Focused received again","source":"LoggingHandler","duration":792.693}],"queryID":"XX"}

**Comment by molybdaen** [comment]
The "content" attribute is always supposed to be an object (not an array). Whatever you wrap inside this object is up to you, in case of "logging.moduleStatisticsCollected".

**Comment by gerwald** [comment]
Super, that looks good now, thanks!
