### ISSUE TITLE
Dashboard does not arrive to getDetails call and fails with _map is not a function

### ISSUE THREAD

**Issue by gdoppler** [EEXCESS/visualization-widgets#11]
applies to the version https://eexcess.github.io/visualization-widgets/Dashboard/starter.js 
The dashboard stays empty, the recommend call gets 36 results. 
The trouble appears using Chrome 42.0, but not using Firefox 41.0.2. 
Furthermore it just appears if the Dashboard is configured to show the embedCitation, embedImage, links. 

In the console I found 
Querying for text: "Cascais"
/lib/requirejs.php/1445013544/core/first.js:31 pdetect
/lib/requirejs.php/1445013544/core/first.js:31 Object
/lib/requirejs.php/1445013544/core/first.js:32 Object
starter.js:85 New data received ...
starter.js:12 Data requested successfully
starter.js:280 Uncaught TypeError: _.map is not a function
loadEexcessDetails @ starter.js:280
onDataReceived @ starter.js:27
requestVisualization @ starter.js:56
window.onmessage @ starter.js:86

**Comment by gerwald** [comment]
hopefully resolved - at least, I cannot reproduce it now
