### ISSUE TITLE
[SearchResultList] indicate #results in filter bar

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#14]
Indicate the number of results for the particular media type in the filter bar. For example, images (23), text (42), audio (0), ...
This way, the user will not be disappointed, when filtering for a particular media type and having no results. 
Another option might be to only display applicable filters, i.e. if there are no audio results, don't display the audio filter. Drawback of this solution: less consistency

**Comment by LadyBytes** [comment]
I chose to add both. The number is displayed in brackets, the filter button is hidden when there are now results. Let me know if you'd prefer just the brackets. 
Hiding the filters makes sense though, as it is a real space-saver.

<img width="265" alt="screen shot 2015-11-04 at 19 08 24" src="https://cloud.githubusercontent.com/assets/3264627/10947288/7146e27e-8327-11e5-8f93-0309d7b57bcd.png">

**Comment by schloett** [comment]
I tend towards hiding the filters, when there are no corresponding results. It's less consistent, but not that bad, since results other than text or images show up very rarely. Also, the UI looks more clean and simply without unusable filters. @chseifert what do you think?
Regarding colors, I would only switch a white text color, when the background is dark green. (show all, original order, title, date). For the other buttons, the text is hard to read otherwise.

**Comment by mgrani** [comment]
hiding is a very good option from my point of view
