### ISSUE TITLE
[SearchResultList] sort by date

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#17]
Beneath 'original order' and 'title', provide a filter that allows to order by date.

**Comment by LadyBytes** [comment]
Please bear in mind that the date data we get in the result isn't the most consistent. Therefore the sorting won't be very reliable.

**Comment by schloett** [comment]
According to https://github.com/EEXCESS/recommender/issues/21, at least the format should be consistent now. I don't know if the date field can be empty, in this case, putting it front or end would be viable solutions imho. Still we don't know what the date exactly describes (creation, discovery, added to collection, ...), but that's an issue that probably won't fix.
