### ISSUE TITLE
[SearchResultList] center title (vertically) in image results

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#21]
When the title only comprises one line, it is perfectly centered. For two lines, the padding at the top is larger than at the bottom. These should be equal.

**Comment by schloett** [comment]
Not sure if this is caused by this fix, but the title area should always have the same size (if the title does not fit into this area it should be cut). If I remember correctly, this had already been the case, but is not anymore.

**Comment by M3hrL1cht** [comment]
should be fixed with latest commit https://github.com/EEXCESS/visualization-widgets/commit/dd66070da9961a12958a639c7fb6e3644943c9bb

**Comment by LadyBytes** [comment]
<img width="1081" alt="screen shot 2015-11-12 at 11 50 49" src="https://cloud.githubusercontent.com/assets/3264627/11116736/caa9433a-8934-11e5-9b07-9b93cb476214.png">

**Comment by schloett** [comment]
:+1:
