### ISSUE TITLE
[search bar] apply filter (all/persons/locations) to new query

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#22]
When the filter is set, it should also be applied, when the query changes. 
Other option might be to reset the filter upon a new query.
This issue relates to #25 (Persisting main topic filters probably makes no sense, therefore resetting the filter seems to be the better option. On the other hand, if a user is only interested in persons, persisting the filter is desirable. Maybe two different behaviors might be encoded in the filter menu)

**Comment by LadyBytes** [comment]
Please ignore my commit, typo in #issue.
