### ISSUE TITLE
[searchResultList] Cluttered searchResultList without text

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/visualization-widgets#36]
Search result list becomes cluttered when a lot of text is present. See the image below.

<img width="1271" alt="screen shot 2015-11-08 at 20 18 08" src="https://cloud.githubusercontent.com/assets/1941683/11022071/dcb2eb12-8655-11e5-8bdc-3f0d66751c4c.png">

**Comment by mgrani** [comment]
...website was https://en.wikipedia.org/wiki/Parachute (paragraph early renessaince)

**Comment by schloett** [comment]
Looks like this behavior has been introduced with the fix of issue #21

**Comment by schloett** [comment]
The fix seems to break the fix of #21 :(
![center](https://cloud.githubusercontent.com/assets/4618499/11088700/833c257e-8864-11e5-9071-bdb54ed60d88.PNG)

**Comment by LadyBytes** [comment]
I know! And I'm on it, the text just doesn't want to budge yet.
