### ISSUE TITLE
[VisDashboard] Feedback 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/visualization-widgets#38]
I got another feedback from a user (per mail) 
"I just found out that I have to enlarge the window manually by first moving it to the middle of my screen, because it can only be enlarged by pulling on the right side of the window. That makes sense somehow but the usability is not yet the best. Maybe change the error message or offer a button to maximize window?
"This visualization requires a larger screen area.
Minimum width 750px and minimum height 200px.""

Users expect that their messages are read, thus I would remove the feedback possibility for the visualisation (that logs the content) completely - and just go with the feedback button in the extension. 
Or at least we should make sure that the feedback is read. 

Related to https://github.com/EEXCESS/visualization-widgets/issues/37 and https://github.com/EEXCESS/chrome-extension/issues/44

**Comment by gerwald** [comment]
showing the feedback textbox when the screen is too small, was bug. it is now solved.
