### ISSUE TITLE
[PowerSearch] initialize with current query

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#4]
Initialize the PowerSearch with the current query profile. This means listening to 'eexcess.queryTriggerd' events and display the attributes in the corresponding fields.

**Comment by treml05** [comment]
initialized

**Comment by schloett** [comment]
Beneath `contextKeywords`, `contextNamedEntities` as well as `timeRange` might also contain values already. If this is the case, these values should be present in the corresponding fields (who, where, start/end).

**Comment by treml05** [comment]
Now it gets fully initialized. ✔
