### ISSUE TITLE
[search result list] more results displayed than available?

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#41]
Sometimes it looks like there are more results displayed than actually available? This might be caused by the handling of resultGroups. (The result array in the server's response has 100 entries).
![sl](https://cloud.githubusercontent.com/assets/4618499/11088586/bcd54adc-8863-11e5-95a3-d88dffd15698.PNG)

**Comment by LadyBytes** [comment]
That's happening because I'm currently figuring out how many result classes I actually need (withAbstract&&withPreview, withAbstract&&!withPreview...) which affects my iostope filtering. Should be fixed later today!
