### ISSUE TITLE
[Visdashboard] Mini Visualisations are not showing on the right side in my browser

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/visualization-widgets#46]
see screenshot. happens in chrome Version 46.0.2490.86 (64-bit) on Mac OS X El Capitan. no exceptions found on console.
![unbenannt-1](https://cloud.githubusercontent.com/assets/1941683/11179003/b66e9be4-8c50-11e5-8e00-86683d44ee70.png)

**Comment by gerwald** [comment]
Should be solved within the newest version. I could reproduce it, when setting google chrome on windows to 90% zoom
