### ISSUE TITLE
[dashboard] Geo Coordinates not correctly displayed

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/visualization-widgets#54]
On the page https://en.wikipedia.org/wiki/Liestal paragraph Geography and setting num. of results to 100 yields 9 geographic results. however, they are located in Jemen (i guess 0,0 from the Geo Coordinates point of view) 

![image](https://cloud.githubusercontent.com/assets/1941683/11457042/68bafbf6-969e-11e5-9d8c-01abbdb9e0c9.png)

**Comment by gerwald** [comment]
Doesnt seem to behave equaly all the time. I just tried to reproduce the bug by following your description, but I do not get any geo results. Any Ideas?

![image](https://cloud.githubusercontent.com/assets/183683/11529899/665ef5e8-98f0-11e5-9b51-267bbbd92749.png)

**Comment by schloett** [comment]
You may hide the languages in your profile. When I disclose "English" I do not get any results from Europeana (and those seem to be the ones with the geo-coordinates).

**Comment by gerwald** [comment]
aah... that helps :) thanks @schloett!

**Comment by gerwald** [comment]
So, got the error... it seems that latitude and longitude are switched in the data, that the dashboard receives.

![image](https://cloud.githubusercontent.com/assets/183683/11531409/064d2460-98fd-11e5-8d44-337a156a2c5e.png)

**Comment by jr-dig-orgel** [comment]
I have checked that.

We get the wrong data from the service with this item.
This get from the service:
        <places>
            <e>
                <about>ort_dargestellt_uuid=e0064797-4543-e64b-3b36-e78553f58411</about>
                <latitude>7.73446</latitude>
                <longitude>47.48455</longitude>
                <prefLabel>
                    <def>
                        <e>Liestal</e>
                    </def>
                </prefLabel>
            </e>
        </places>

And this is the same as on the webPage:
http://europeana.eu/resolve/record/2058620/e0064797_4543_e64b_3b36_e78553f58411
and of course this wrong, but europeana must change this.

I have also checked the mapping and this is correct.
