### ISSUE TITLE
FacetScape: when increasing window size, increase the result list size too

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/visualization-widgets#9]
Current behaviour: when increasing the size of the pane, the facetscape is increased, but the result list stays the same. This is an unintuitive behaviour. 

Suggested solution: either add a draggable splitter between the result list and the facet scape such that hte user can chose the relativ height between both or increase facet scape as well as result list when increasing the height of the visualisation.

**Comment by molybdaen** [comment]
Fixed. Now, both the voronoi-viz and the result list take up 50% of the available space each. -> (b762bc4dc)
